---
- hosts: all
  tasks:
    - name: 'instala todas as dependencias servidor web wordpress'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php
        - apache2
        - libapache2-mod-php
        - php-gd
        - php-ssh2
        - php-mcrypt
        - mysql-server
        - python-mysqldb
        - php-mysql

    - name: 'Criando o banco de dados'
      mysql_db:
        name: wp_db
        state: present
        login_user: root
      become: yes

    - name: 'Criando usuario para o db wordpress'
      mysql_user:
        name: wp
        password: fuckoff
        priv: 'wp_db.*:ALL'
        state: present
        login_user: root
      become: yes

    - name: 'Baixando wordpress para tmp'
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        checksum: md5:f168643b20001cc46b3478facd4f539b

    - name: 'Descompactando wordpress em tmp'
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www"
        remote_src: yes
      become: yes

    - name: 'Copiando wp-config'
      copy:
        src: "/var/www/wordpress/wp-config-sample.php"
        dest: "/var/www/wordpress/wp-config.php"
        remote_src: yes
      become: yes

    - name: 'Configurando wp-config'
      replace:
        path: "/var/www/wordpress/wp-config.php"
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
        #backup: yes
      with_items:
        - { regex: 'database_name_here' ,value: 'wp_db' }
        - { regex: 'username_here' ,value: 'wp' }
        - { regex: 'password_here' ,value: 'fuckoff' }
         # - { regex: ''}
      become: yes
